### PR TITLE
input/output expose for AOT

### PR DESCRIPTION
**Pull request by day01**
In the PR:
* removed "dist" from git repository (there were lot of unnecessary diffs when compiling) - js should be in npm package, doesn't in git
* input/output expose for AOT (based on ngc-pre-compiler.js)

### CODE REVIEW

**Comment by allenhwkim** [comment]
I feel hesitant to accept this PR because INPUTS/OUTPUTS are redundant.
for example `center` is defined twice in INPUTS and @Input.
The same goes for OUTPUTS and @Output

```
const INPUTS = [
  'center', 'clickable', 'draggable', 'editable', 'fillColor', 'fillOpacity', 'map', 'radius',
  'strokeColor', 'strokeOpacity', 'strokePosition', 'strokeWeight', 'visible', 'zIndex', 'options',
  // ng2-map specific inputs
  'geoFallbackCenter'
];
const OUTPUTS = [
  'centerChanged', 'click', 'dblclick', 'drag', 'dragend', 'dragstart',
  'mousedown', 'mousemove', 'mouseout', 'mouseover', 'mouseup', 'radiusChanged', 'rightclick',
];

@Directive({
  selector: 'ng2-map>circle, ng2-map>map-circle',
})
export class Circle extends BaseMapDirective {
  @Output() public centerChanged: EventEmitter<any> = new EventEmitter(); // generated by ngc-pre-compiler.js
 ...
  @Output() public initialized$: EventEmitter<any> = new EventEmitter();

  @Input() public center: any; // generated by ngc-pre-compiler.js
   ... 
 @Input() public geoFallbackCenter: any; // generated by ngc-pre-compiler.js
```

Unlesss we can totally remove INPUTS and OUTPUTS, I would rather stick to `INPUTS` and `OUTPUTS` for simplicity.

**Comment by day01** [comment]
INPUTS, OUTPUTS arrays are in the code because:
For e.g. circle.ts
`super(ng2MapComp, 'Circle', INPUTS, OUTPUTS);`

for BaseMapDirective.
`this.objectOptions = this.optionBuilder.googlizeAllInputs(this.inputs, this);`
`this.ng2Map.setObjectEvents(this.outputs, this, 'mapObject');`
`this.outputs.forEach(output => google.maps.event.clearListeners(this.mapObject, output));`

A lot of logic in baseMapDirective are correlated with the arrays. I won't change that part. If you have an idea how to correctly change baseMapDircetive then I will change. But in my opinion that part is ok.

**Comment by aitboudad** [comment]
@day01 can you open a separate PR for removing the `dist` folder.

**Comment by allenhwkim** [comment]
I would like close this PR and I really not want to have @Inputs/@Outputs and INPUTS/OUTPUTS together. I only want one. I will stick to  INPUTS/OUTPUTS  at this time until there is a solution to totally remove INPUTS and OUTPUTS.

**Pull request closed without merging**
