### PR TITLE
export NG_MAP_CONFIG_TOKEN + fixed ngc issue.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by allenhwkim** [comment]
Does this solve https://github.com/ng2-ui/ng2-map/issues/54?

**Comment by aitboudad** [comment]
I'm not sure but the AOT work for me without any issue

**Comment by ujibang** [comment]
Hi @aitboudad how do you configure the Ng2MapComponent

if I put `Ng2MapModule.forRoot({apiUrl: 'https://maps.google.com/maps/api/js?key=MY_GOOGLE_API_KEY')` between the imports of app.module.ts it works with `ng s` but fails compilation with AOT

**Comment by aitboudad** [comment]
@ujibang can create a new issue and provide us a repo with the changes to reproduce it.

**Comment by aitboudad** [comment]
also make sure you use the latest version of `angular`

**Pull request merged**
