### PR TITLE
Now it is possible to use ng2-map with other google APIs

### PR DESCRIPTION
**Pull request by matvey-kazakov**
This is the fix for allowing other google APIs like charts in the same project.
I don't understand why `ngc` generated different code for all components. Difference is the same:
instead of 
`InfoWindow.ctorParameters = [
...
];`
it generated
`InfoWindow.ctorParameters = function () { return [
...
]; };`

Apart from that changes concern two typescript files (`ng2-map.component.ts` and `places-auto-complete.ts`) and compiled `ng2-map.umd.js` has only required changes.  This fix helped me to use Google Charts on the same page with ng2-map

### CODE REVIEW

**Comment by allenhwkim** [comment]
Thanks, but I think you made a mistake with `window['google.maps']`
image

**Comment by matvey-kazakov** [comment]
You're right. It should have been 
(!window['google'] || !window['google']['maps'])

**Comment by allenhwkim** [comment]
Could you merge your branch with master again and make PR so that conflicts are resolved?

**Comment by allenhwkim** [comment]
This has been merged

**Pull request closed without merging**
