### PR TITLE
Concurrency fix during property update ;  events available as outputs

### PR DESCRIPTION
**Pull request by caerulea-rosa**
Concurrency fix - when several properties change at the same time, the correct value us now updated - not just the last one

... previously, the setMethodName could change before the subscription actually got executed

... also, adds @Output() to initialized$ and mapReady$

### CODE REVIEW

**Comment by caerulea-rosa** [comment]
Thank you very much! :)

**Comment by caerulea-rosa** [comment]
Just to make things right for now, this is an example of when it happens : https://plnkr.co/edit/9DZSVj4EP3FObCpdGiko?p=preview

**Comment by caerulea-rosa** [comment]
If you do not mind my asking :  how often do you release it? And when do you think this might get to npm? :) Locally, I have the changes, but on the build computer, I would need to overwrite the repo and would like to avoid that if I can.

Thank you :)

**Comment by allenhwkim** [comment]
After merge,
*  I need to do code review to make it sure it works as intended
* I need to run test 
* I need to build a test for this use case if necessary
* I run the test again
* and build and release

How often? as often as possible :), and maybe today at this Starbucks

FYI, you can also use a chat room. You can find a link at README.md

**Pull request merged**
